const products=[
    {
        id:1,
        name:"Nike Air Jordan 4",
        price:120.00,
        image:"/images/mens_footwear_img/nike jordan",
        rating:4.5,
        category:"Sneakers",
    },
    {
        id:2,
        name:"Adidas Supernove",
        price:98.20,
        image:"/images/womens_footwear_img/adidas",
        rating:4.3,
        category:"Running Shoes",
    },
    {
        id:3,
        name:"Puma X-Ray Sneakers",
        price:95.00,
        image:"/images/mens_footwear_img/puma_X",
        rating:4.9,
        category:"Sneakers",
    },
    {
        id:4,
        name:"Vegan Biker Boots",
        price:31.95,
        image:"/images/womens_footwear_img/boots",
        rating:3.8,
        category:"Boots",
    },
    {
        id:5,
        name:"New Balance 370",
        price:63.00,
        image:"/images/mens_footwear_img/new_balance_360",
        rating:4.1,
        category:"Sneakers",
    },
    {
        id:6,
        name:"Puma Palermo",
        price:80.71,
        image:"/images/mens_footwear_img/puma_paliramo",
        rating:4.6,
        category:"Sneakers",
    },
    {
        id:7,
        name:"Nike Full Force Low",
        price:111.32,
        image:"/images/mens_footwear_img/nike_full_force",
        rating:5.0,
        category:"Sneakers",
    },
    {
        id:8,
        name:"Mayze Leather",
        price:32.22,
        image:"/images/womens_footwear_img/womens_maze",
        rating:2.9,
        category:"Sneakers",
    },
    {
        id:9,
        name:"Nike Court Vision Low Shoes",
        price:77.89,
        image:"/images/mens_footwear_img/nike_cour_low_vision2.webp",
        rating:4.7,
        category:"Sneakers",
    },

{
        id:10,
        name:"New Balance 574 Core Women's",
        price:103.00,
        image:"/images/womens_footwear_img/new_balance_530",
        rating:4.3,
        category:"Sneakers",
    },
    {
        id:11,
        name:"Reebok Running Shoes",
        price:48.50,
        image:"/images/mens_footwear_img/reebok_image",
        rating:4.1,
        category:"Running Shoes",
    },
    {
        id:12,
        name:"Strappy Heels",
        price:31.00,
        image:"/images/womens_footwear_img/JM LOOKS Strappy Heels",
        rating:3.0,
        category:"Heels",
    },
    {
        id:13,
        name:"Block Heels",
        price:29.54,
        image:"/images/womens_footwear_img/Roadstar hhels",
        rating:4.6,
        category:"Heels",
    },
      {
        id:14,
        name:"Puma Speedcat Faded Sneakers",
        price:78.00,
        image:"/images/mens_footwear_img/Puma Speedcat Faded Sneakers",
        rating:4.5,
        category:"Sneakers",
    },
      {
        id:15,
        name:"DressBerry Block Heels",
        price:60.9,
        image:"/images/womens_footwear_img/DressBerry.webp",
        rating:4.8,
        category:"Heels",
    },
]

export default products;

